//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsolaWaltMart
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoWallmart
    {
        public string UPC { get; set; }
        public string Descripcion { get; set; }
        public string Precio { get; set; }
        public int IDProductoWallmart { get; set; }
    }
}
